// Generated by scripts/generate_sfp_dual_drp.py; edit reviewed drp_fields.json.
module sfp_dual_drp_rom(input wire [5:0] index, input wire mode_10g,
 output reg [9:0] address, output reg [15:0] mask, value, output wire last);
assign last=(index==6'd36);
always @* begin
 address=0; mask=0; value=0;
 case(index)
 // RX_DATA_WIDTH
 6'd0: begin address=10'h003; mask=16'h01e0; value=mode_10g ? 16'h00c0 : 16'h0060; end
 // RXCDR_CFG2
 6'd1: begin address=10'h010; mask=16'hffff; value=mode_10g ? 16'h0269 : 16'h0239; end
 // RXCDR_CFG3
 6'd2: begin address=10'h011; mask=16'hffff; value=mode_10g ? 16'h0010 : 16'h0012; end
 // CLK_COR_KEEP_IDLE, CLK_COR_MIN_LAT
 6'd3: begin address=10'h01c; mask=16'h007f; value=mode_10g ? 16'h0012 : 16'h004b; end
 // CLK_COR_MAX_LAT, CLK_COR_SEQ_LEN
 6'd4: begin address=10'h01d; mask=16'hfc0c; value=mode_10g ? 16'h5000 : 16'h3804; end
 // CLK_COR_SEQ_1_1
 6'd5: begin address=10'h01e; mask=16'h03ff; value=mode_10g ? 16'h0000 : 16'h01bc; end
 // CLK_COR_SEQ_1_2
 6'd6: begin address=10'h01f; mask=16'h03ff; value=mode_10g ? 16'h0000 : 16'h0050; end
 // CLK_COR_SEQ_2_1
 6'd7: begin address=10'h022; mask=16'h03ff; value=mode_10g ? 16'h0000 : 16'h01bc; end
 // CLK_COR_SEQ_2_2
 6'd8: begin address=10'h023; mask=16'h03ff; value=mode_10g ? 16'h0000 : 16'h00b5; end
 // CLK_CORRECT_USE, CLK_COR_SEQ_2_USE
 6'd9: begin address=10'h024; mask=16'h0c00; value=mode_10g ? 16'h0000 : 16'h0c00; end
 // ALIGN_COMMA_ENABLE
 6'd10: begin address=10'h027; mask=16'h03ff; value=mode_10g ? 16'h0000 : 16'h03ff; end
 // DEC_PCOMMA_DETECT
 6'd11: begin address=10'h02c; mask=16'h8000; value=mode_10g ? 16'h0000 : 16'h8000; end
 // TX_PROGDIV_CFG
 6'd12: begin address=10'h03e; mask=16'hffff; value=mode_10g ? 16'he218 : 16'h8000; end
 // ALIGN_MCOMMA_DET
 6'd13: begin address=10'h055; mask=16'h0400; value=mode_10g ? 16'h0000 : 16'h0400; end
 // ALIGN_PCOMMA_DET
 6'd14: begin address=10'h056; mask=16'h0400; value=mode_10g ? 16'h0000 : 16'h0400; end
 // RX_SUM_IREF_TUNE, RX_SUM_VCMTUNE
 6'd15: begin address=10'h062; mask=16'h1e78; value=mode_10g ? 16'h1250 : 16'h0830; end
 // CBCC_DATA_SOURCE_SEL, RXOUT_DIV
 6'd16: begin address=10'h063; mask=16'h8007; value=mode_10g ? 16'h0000 : 16'h8003; end
 // RXBUF_EN, RXGEARBOX_EN
 6'd17: begin address=10'h064; mask=16'h0009; value=mode_10g ? 16'h0001 : 16'h0008; end
 // RXBUF_RESET_ON_COMMAALIGN, RX_INT_DATAWIDTH, RX_WIDEMODE_CDR
 6'd18: begin address=10'h066; mask=16'h400f; value=mode_10g ? 16'h0005 : 16'h4000; end
 // RXBUF_ADDR_MODE
 6'd19: begin address=10'h067; mask=16'h0001; value=mode_10g ? 16'h0001 : 16'h0000; end
 // TXPHDLY_CFG1
 6'd20: begin address=10'h06f; mask=16'hffff; value=mode_10g ? 16'h000e : 16'h000f; end
 // TXPH_CFG
 6'd21: begin address=10'h073; mask=16'hffff; value=mode_10g ? 16'h0323 : 16'h0723; end
 // TX_DATA_WIDTH
 6'd22: begin address=10'h07a; mask=16'h000f; value=mode_10g ? 16'h0006 : 16'h0003; end
 // TXBUF_EN, TXGEARBOX_EN, TXOUT_DIV
 6'd23: begin address=10'h07c; mask=16'h2780; value=mode_10g ? 16'h2000 : 16'h0380; end
 // TX_INT_DATAWIDTH
 6'd24: begin address=10'h085; mask=16'h0c00; value=mode_10g ? 16'h0400 : 16'h0000; end
 // RXSYNC_SKIP_DA
 6'd25: begin address=10'h08a; mask=16'h0100; value=mode_10g ? 16'h0000 : 16'h0100; end
 // GEARBOX_MODE
 6'd26: begin address=10'h099; mask=16'hf800; value=mode_10g ? 16'h8800 : 16'h0000; end
 // TXPI_CFG4
 6'd27: begin address=10'h09c; mask=16'h0020; value=mode_10g ? 16'h0000 : 16'h0020; end
 // RXPI_CFG0
 6'd28: begin address=10'h09d; mask=16'hffff; value=mode_10g ? 16'h0002 : 16'h0102; end
 // RXCDR_CFG2_GEN3
 6'd29: begin address=10'h0a4; mask=16'hffff; value=mode_10g ? 16'h0269 : 16'h0239; end
 // RXCDR_CFG3_GEN3
 6'd30: begin address=10'h0a5; mask=16'hffff; value=mode_10g ? 16'h0010 : 16'h0012; end
 // PCIE_TXPCS_CFG_GEN3
 6'd31: begin address=10'h0aa; mask=16'hffff; value=mode_10g ? 16'h2ca4 : 16'h24a4; end
 // PCIE_PLL_SEL_MODE_GEN12, PCIE_PLL_SEL_MODE_GEN3
 6'd32: begin address=10'h0ad; mask=16'h1e00; value=mode_10g ? 16'h1400 : 16'h1800; end
 // RXCDR_CFG2_GEN2, RXCDR_CFG3_GEN2
 6'd33: begin address=10'h0af; mask=16'hffff; value=mode_10g ? 16'h4269 : 16'h4a39; end
 // PCIE_BUFG_DIV_CTRL
 6'd34: begin address=10'h0c3; mask=16'hffff; value=mode_10g ? 16'h3500 : 16'h1000; end
 // RX_PROGDIV_CFG
 6'd35: begin address=10'h0c6; mask=16'hffff; value=mode_10g ? 16'he218 : 16'h8000; end
 // DEC_MCOMMA_DETECT
 6'd36: begin address=10'h0cd; mask=16'h0001; value=mode_10g ? 16'h0000 : 16'h0001; end
 endcase
end
endmodule
