# Regenerate in a build directory; caller provides an open K26 project.
create_ip -name gtwizard_ultrascale -vendor xilinx.com -library ip -module_name gth_sfp_10g_ip
set_property CONFIG.preset GTH-10GBASE-R [get_ips gth_sfp_10g_ip]
set_property -dict [list CONFIG.CHANNEL_ENABLE X0Y6 \
 CONFIG.TX_MASTER_CHANNEL X0Y6 CONFIG.RX_MASTER_CHANNEL X0Y6 \
 CONFIG.TX_LINE_RATE 10.3125 CONFIG.RX_LINE_RATE 10.3125 \
 CONFIG.TX_REFCLK_FREQUENCY 156.25 CONFIG.RX_REFCLK_FREQUENCY 156.25 \
 CONFIG.TX_USER_DATA_WIDTH 64 CONFIG.RX_USER_DATA_WIDTH 64 \
 CONFIG.TX_INT_DATA_WIDTH 32 CONFIG.RX_INT_DATA_WIDTH 32 \
 CONFIG.LOCATE_COMMON CORE CONFIG.LOCATE_RESET_CONTROLLER CORE \
 CONFIG.LOCATE_TX_USER_CLOCKING CORE CONFIG.LOCATE_RX_USER_CLOCKING CORE \
 CONFIG.LOCATE_USER_DATA_WIDTH_SIZING CORE CONFIG.FREERUN_FREQUENCY 50 \
 CONFIG.ENABLE_OPTIONAL_PORTS {qpll0lock_out}] [get_ips gth_sfp_10g_ip]
