# Existing 1G SFP clock-pair bounds, sourced by kr260_clocks.xdc.
set_max_delay -datapath_only -from [get_clocks clk_pl_0] -to [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] 7.000
set_max_delay -datapath_only -from [get_clocks clk_pl_0] -to [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] 7.000
set_max_delay -datapath_only -from [get_clocks clk_out3_pl_eth_clk_gen_ip] -to [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out3_pl_eth_clk_gen_ip] -to [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_pl_eth_clk_gen_ip] -to [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_pl_eth_clk_gen_ip] -to [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_pl_eth_clk_gen_ip_1] -to [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_pl_eth_clk_gen_ip_1] -to [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_pl_0] 7.000
set_max_delay -datapath_only -from [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_out3_pl_eth_clk_gen_ip] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_out1_pl_eth_clk_gen_ip] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out1_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_out1_pl_eth_clk_gen_ip_1] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_pl_0] 7.000
set_max_delay -datapath_only -from [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_out3_pl_eth_clk_gen_ip] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_out1_pl_eth_clk_gen_ip] 8.000
set_max_delay -datapath_only -from [get_clocks clk_out2_sfp_pcs_clk_gen_ip*] -to [get_clocks clk_out1_pl_eth_clk_gen_ip_1] 8.000
