#!/usr/bin/env python3
"""Generate masked, reversible GTHE4 DRP writes from reviewed UG576 fields.
With --profiles, reject Wizard parameter drift before emitting the ROM.
"""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--profiles',type=Path)
p.add_argument('--output',type=Path,default=ROOT/'rtl/sfp_dual/sfp_dual_drp_rom.sv')
a=p.parse_args(); spec=json.loads((ROOT/'rtl/sfp_dual/ip/drp_fields.json').read_text())
if a.profiles:
    profiles=[]
    for name in ('gth_sfp_ip','gth_sfp_dual_ip'):
        f=next(a.profiles.rglob(name+'_gthe4_channel_wrapper.v'))
        profiles.append({k.removeprefix('GTHE4_CHANNEL_'):v.strip() for k,v in re.findall(r'\.(GTHE4_CHANNEL_\w+)\s*\(([^()]+)\)',f.read_text())})
    expected={f['attribute']:f['wizard_values'] for f in spec['fields']}|spec['ports']
    actual={k:[profiles[0][k],profiles[1][k]] for k in profiles[0] if k in profiles[1] and profiles[0][k]!=profiles[1][k]}
    assert actual==expected, f'Unreviewed GT profile change: {actual.keys() ^ expected.keys()} or differing values'
regs={}
for f in spec['fields']:
    mask=((1<<f['width'])-1)<<f['lsb']
    r=regs.setdefault(f['address'],[0,0,0,[]]); assert not r[0]&mask
    r[0]|=mask
    for mode in (0,1):
        assert f['values'][mode] < 1<<f['width']
        r[1+mode]|=f['values'][mode]<<f['lsb']
    r[3].append(f['attribute'])
s=['// Generated by scripts/generate_sfp_dual_drp.py; edit reviewed drp_fields.json.',
   'module sfp_dual_drp_rom(input wire [5:0] index, input wire mode_10g,',
   ' output reg [9:0] address, output reg [15:0] mask, value, output wire last);',
   f"assign last=(index==6'd{len(regs)-1});",'always @* begin',' address=0; mask=0; value=0;',' case(index)']
for i,(addr,(mask,v1,v10,names)) in enumerate(sorted(regs.items())):
    s += [' // '+', '.join(names),f" 6'd{i}: begin address=10'h{addr:03x}; mask=16'h{mask:04x}; value=mode_10g ? 16'h{v10:04x} : 16'h{v1:04x}; end"]
s+=[' endcase','end','endmodule',''];a.output.write_text('\n'.join(s))
print(f'{len(regs)} DRP registers, {len(spec["fields"])} reviewed fields')
