// GEM external FIFO port, CDC and local clear-on-read counter banks.
module switch_gem_port (
  input wire  clk,
  input wire  rst_n,
  input wire  gem_rx_clk,
  input wire  gem_rx_rst_n,
  input wire  gem_tx_clk,
  input wire  gem_tx_rst_n,
  input wire [7:0]   rx_w_data_i,
  input wire  rx_w_wr_i,
  input wire  rx_w_sop_i,
  input wire  rx_w_eop_i,
  input wire  rx_w_err_i,
  input wire  rx_w_flush_i,
  input wire [44:0]  rx_w_status_i,
  output wire  rx_w_overflow_o,
  output wire [15:0]  m_axis_tdata,
  output wire [1:0]   m_axis_tkeep,
  output wire  m_axis_tvalid,
  output wire  m_axis_tlast,
  output wire  m_axis_tuser,
  input wire  m_axis_tready,
  output wire [44:0]  rx_w_status_o,
  input wire [15:0]  s_axis_tdata,
  input wire [1:0]   s_axis_tkeep,
  input wire  s_axis_tvalid,
  input wire  s_axis_tlast,
  output wire  s_axis_tready,
  input wire  tx_r_rd_i,
  output wire  tx_r_data_rdy_o,
  output wire  tx_r_valid_o,
  output wire [7:0]  tx_r_data_o,
  output wire  tx_r_sop_o,
  output wire  tx_r_eop_o,
  output wire  tx_r_err_o,
  output wire  tx_r_underflow_o,
  output wire  tx_r_flushed_o,
  output wire  tx_r_control_o,
  input wire  dma_tx_end_tog_i,
  output wire  dma_tx_status_tog_o,
  input wire [3:0]  tx_r_status_i,
  input wire [1:0] stats_req,
  input wire [3:0] stats_select,
  output wire [1:0] stats_acks,
  output wire [1:0][31:0] stats_values
);
  ps_gem_axis_bridge u_bridge (
    .clk(clk),
    .rst_n(rst_n),
    .gem_rx_clk(gem_rx_clk),
    .gem_rx_rst_n(gem_rx_rst_n),
    .gem_tx_clk(gem_tx_clk),
    .gem_tx_rst_n(gem_tx_rst_n),
    .rx_w_data_i(rx_w_data_i),
    .rx_w_wr_i(rx_w_wr_i),
    .rx_w_sop_i(rx_w_sop_i),
    .rx_w_eop_i(rx_w_eop_i),
    .rx_w_err_i(rx_w_err_i),
    .rx_w_flush_i(rx_w_flush_i),
    .rx_w_status_i(rx_w_status_i),
    .rx_w_overflow_o(rx_w_overflow_o),
    .m_axis_tdata(m_axis_tdata),
    .m_axis_tkeep(m_axis_tkeep),
    .m_axis_tvalid(m_axis_tvalid),
    .m_axis_tlast(m_axis_tlast),
    .m_axis_tuser(m_axis_tuser),
    .m_axis_tready(m_axis_tready),
    .rx_w_status_o(rx_w_status_o),
    .s_axis_tdata(s_axis_tdata),
    .s_axis_tkeep(s_axis_tkeep),
    .s_axis_tvalid(s_axis_tvalid),
    .s_axis_tlast(s_axis_tlast),
    .s_axis_tready(s_axis_tready),
    .tx_r_rd_i(tx_r_rd_i),
    .tx_r_data_rdy_o(tx_r_data_rdy_o),
    .tx_r_valid_o(tx_r_valid_o),
    .tx_r_data_o(tx_r_data_o),
    .tx_r_sop_o(tx_r_sop_o),
    .tx_r_eop_o(tx_r_eop_o),
    .tx_r_err_o(tx_r_err_o),
    .tx_r_underflow_o(tx_r_underflow_o),
    .tx_r_flushed_o(tx_r_flushed_o),
    .tx_r_control_o(tx_r_control_o),
    .dma_tx_end_tog_i(dma_tx_end_tog_i),
    .dma_tx_status_tog_o(dma_tx_status_tog_o),
    .tx_r_status_i(tx_r_status_i)
  );
  wire [3:0][31:0] stats_rx_inc;
  stats_gem_rx stats_rx (.clk(gem_rx_clk),.rst_n(gem_rx_rst_n),
    .wr(rx_w_wr_i),.sop(rx_w_sop_i),.eop(rx_w_eop_i),.error(rx_w_err_i),.flush(rx_w_flush_i),.overflow(rx_w_overflow_o),.increment(stats_rx_inc));
  stats_bank #(.N(4)) stats_bank0 (.clk(gem_rx_clk),.rst_n(gem_rx_rst_n),
    .increment(stats_rx_inc),.request(stats_req[0]),.select(stats_select),.ack(stats_acks[0]),.value(stats_values[0]));
  wire [3:0][31:0] stats_tx_inc;
  stats_gem_tx stats_tx (.clk(gem_tx_clk),.rst_n(gem_tx_rst_n),
    .valid(tx_r_valid_o),.sop(tx_r_sop_o),.error(tx_r_err_o),.underflow(tx_r_underflow_o),.complete_toggle(dma_tx_end_tog_i),.status(tx_r_status_i),.increment(stats_tx_inc));
  stats_bank #(.N(4)) stats_bank1 (.clk(gem_tx_clk),.rst_n(gem_tx_rst_n),
    .increment(stats_tx_inc),.request(stats_req[1]),.select(stats_select),.ack(stats_acks[1]),.value(stats_values[1]));
endmodule
